from reportlab.pdfgen import canvas
from flask import send_file
import io
from flask import Flask, render_template, request, redirect, session
import os
import psycopg2
import pickle
import numpy as np
app = Flask(__name__)
@app.route('/')
def splash():
    return render_template("splash.html")
app.secret_key = "ecopackai_secret"
# ---------------- DATABASE CONNECTION ----------------

DATABASE_URL = os.environ.get("DATABASE_URL")

conn = psycopg2.connect(DATABASE_URL)
cursor = conn.cursor()

print("Database connected successfully")

# ---------------- LOAD ML MODEL ----------------

model = pickle.load(open("ml_model/packaging_model.pkl", "rb"))
le_material = pickle.load(open("ml_model/le_material.pkl", "rb"))


# ---------------- HOME ----------------

@app.route('/home')
def home():
    return render_template("index.html")


# ---------------- LOGIN ----------------

@app.route('/login')
def login():
    return render_template("login.html")


@app.route('/login_user', methods=['POST'])
def login_user():

    email = request.form['email']
    password = request.form['password']

    cursor.execute(
        "SELECT * FROM users WHERE email=%s AND password=%s",
        (email,password)
    )

    user = cursor.fetchone()

    if user:
        session['user'] = email
        return redirect('/predict')
    else:
        return "Invalid login"


# ---------------- SIGNUP ----------------

@app.route('/signup')
def signup():
    return render_template("signup.html")


@app.route('/register', methods=['POST'])
def register():

    name = request.form['name']
    email = request.form['email']
    phone = request.form['phone']
    password = request.form['password']

    cursor.execute(
        "INSERT INTO users (name,email,phone,password) VALUES (%s,%s,%s,%s)",
        (name,email,phone,password)
    )

    conn.commit()

    return redirect('/login')


# ---------------- PREDICT PAGE ----------------

@app.route('/predict')
@app.route('/predict.html')
def predict():

    if 'user' not in session:
        return """
        <script>
        alert('⚠ You need to login first to start recommendation');
        window.location.href='/login';
        </script>
        """

    return render_template("predict.html")


# ---------------- RESULT PAGE ----------------

@app.route('/predict_result', methods=['POST'])
def predict_result():

    durability = float(request.form['durability'])
    weight = float(request.form['weight'])
    biodegradability = float(request.form['biodegradability'])
    recyclability = float(request.form['recyclability'])
    co2 = float(request.form['co2'])

    features = np.array([[durability, weight, biodegradability, recyclability, co2]])

    prediction = model.predict(features)

    material = le_material.inverse_transform(prediction)[0]

    # Save recommendation

    cursor.execute(
        """
        INSERT INTO recommendations
        (user_id, product_category, weight, fragility, distance, material, co2_impact, cost_efficiency)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
        """,
        (
            1,
            "General",
            weight,
            "Medium",
            100,
            material,
            "Low",
            "High"
        )
    )

    conn.commit()

    import random

    score = random.randint(75,95)

    return render_template(
    "result.html",
    material=material,
    score=score
)



@app.route('/download_report/<material>')
def download_report(material):

    buffer = io.BytesIO()

    pdf = canvas.Canvas(buffer)

    pdf.setFont("Helvetica", 16)
    pdf.drawString(200, 800, "EcoPackAI Recommendation Report")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(100, 750, f"Recommended Material: {material}")

    pdf.drawString(100, 720, "Generated by EcoPackAI System")

    pdf.save()

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="EcoPackAI_Report.pdf",
        mimetype="application/pdf"
    )
# ---------------- HISTORY ----------------

@app.route('/history')
@app.route('/history.html')
def history():

    cursor.execute("SELECT id, product_category, material, created_at FROM recommendations ORDER BY created_at DESC")

    data = cursor.fetchall()

    return render_template("history.html", data=data)


@app.route('/delete_history/<int:id>')
def delete_history(id):

    cursor.execute("DELETE FROM recommendations WHERE id=%s", (id,))
    conn.commit()

    return redirect('/history')

# ---------------- PROFILE ----------------

@app.route('/profile')
@app.route('/profile.html')
def profile():

    cursor.execute("SELECT name,email,phone FROM users LIMIT 1")
    user = cursor.fetchone()

    cursor.execute("SELECT COUNT(*) FROM recommendations")
    total = cursor.fetchone()[0]

    return render_template("profile.html", user=user, total=total)


# ---------------- ADMIN ----------------
# ---------------- ADMIN ----------------

# Admin login page (GET)
@app.route('/admin_login')
def admin_login_page():
    return render_template("admin_login.html")


# Admin login processing (POST)
@app.route('/admin_login', methods=['POST'])
def admin_login():

    username = request.form['username']
    password = request.form['password']

    if username == "admin" and password == "admin123":
        return redirect('/admin_dashboard')
    else:
        return "Invalid Admin Login"


# Admin dashboard
@app.route('/admin_dashboard')
def admin_dashboard():

    # Total users
    cursor.execute("SELECT COUNT(*) FROM users")
    total_users = cursor.fetchone()[0]

    # Total recommendations
    cursor.execute("SELECT COUNT(*) FROM recommendations")
    total_recommendations = cursor.fetchone()[0]

    # Most used materials
    cursor.execute("""
        SELECT material, COUNT(material)
        FROM recommendations
        GROUP BY material
        ORDER BY COUNT(material) DESC
    """)

    material_data = cursor.fetchall()

    labels = [row[0] for row in material_data]
    values = [row[1] for row in material_data]

    return render_template(
        "admin_dashboard.html",
        total_users=total_users,
        total_recommendations=total_recommendations,
        labels=labels,
        values=values
    )


@app.route('/admin_users')
def admin_users():

    cursor.execute("SELECT id, name, email, phone FROM users")

    users = cursor.fetchall()

    return render_template("admin_users.html", users=users)
# ---------------- RUN ----------------
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)




